import React, { useState } from 'react';
import { X, Shield, FileText, CheckCircle2, ExternalLink } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';

interface LegalPolicyModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialTab?: 'privacy' | 'terms';
}

export const LegalPolicyModal: React.FC<LegalPolicyModalProps> = ({
  isOpen,
  onClose,
  initialTab = 'privacy'
}) => {
  const [activeTab, setActiveTab] = useState(initialTab);

  const privacyPolicyContent = {
    lastUpdated: "September 18, 2025",
    version: "2.0",
    sections: [
      {
        title: "Information We Collect",
        content: `We collect information you provide directly to us, such as:
        • Mobile phone number for authentication
        • Optional email address for account recovery
        • Physical address for location-based services and advertisements
        • Step count data from your device's sensors
        • Transaction history for wallet management
        • Referral network information`
      },
      {
        title: "How We Use Your Information",
        content: `We use your information to:
        • Provide and maintain the Yogic Mile service
        • Process step tracking and reward calculations
        • Send location-based advertisements and offers
        • Detect and prevent fraudulent activities
        • Communicate with you about your account
        • Improve our services through analytics`
      },
      {
        title: "Information Sharing",
        content: `We may share your information with:
        • Trusted partners for reward fulfillment
        • Advertisers for relevant local deals (anonymized data only)
        • Law enforcement when required by law
        • Service providers who assist in our operations
        
        We never sell your personal information to third parties.`
      },
      {
        title: "Data Security",
        content: `We implement strong security measures:
        • End-to-end encryption for sensitive data
        • Secure OTP authentication system
        • Advanced fraud detection algorithms
        • Regular security audits and monitoring
        • Secure data storage with backup protection`
      },
      {
        title: "Your Rights",
        content: `Under GDPR, you have the right to:
        • Access your personal data
        • Correct inaccurate information
        • Delete your account and data
        • Export your data in a machine-readable format
        • Withdraw consent for data processing
        • File complaints with data protection authorities`
      },
      {
        title: "Data Retention",
        content: `We retain your data as follows:
        • Active account data: While your account is active
        • Transaction records: 7 years for legal compliance
        • Security logs: 3 years for fraud prevention
        • Deleted account data: Permanently removed within 90 days
        • Anonymous analytics: Indefinitely for service improvement`
      },
      {
        title: "Contact Information",
        content: `For privacy-related inquiries:
        • Email: privacy@yogicmile.com
        • Data Protection Officer: dpo@yogicmile.com
        • Postal Address: [Your Company Address]
        • Response time: Within 30 days as required by law`
      }
    ]
  };

  const termsContent = {
    lastUpdated: "September 22, 2025",
    version: "3.0",
    sections: [
      {
        title: "Eligibility & Registration",
        content: `• You must be 18 years or older to sign up and redeem rewards.
• Minors aged 13–17 years may use the App under parental or guardian consent.
• Registration requires a valid Indian mobile number, which will serve as your unique user ID and referral code.
• You may optionally provide email ID and address, which helps us provide personalized coupons, local offers, and advertisements.
• Users must provide accurate, current, and complete information during registration. False or misleading information may result in suspension.`
      },
      {
        title: "Step Tracking & Reward System",
        content: `• Steps are recorded using your device's motion sensors or connected fitness APIs.
• The App applies a daily limit (e.g., 12,000 steps) to ensure fair usage.
• Steps must be naturally generated by walking, jogging, or running. Artificial manipulation (shaking devices, automated step tools, tampering) will result in immediate suspension and forfeiture of rewards.
• Rewards are credited in paise (₹0.01) or equivalent virtual points.
• Conversion rate: 25 steps = 1 paisa (subject to periodic review).
• Rewards are displayed in your in-app wallet and may vary depending on your activity phase, offers, or special campaigns.`
      },
      {
        title: "Wallet & Redemption",
        content: `• The in-app wallet reflects your earned rewards balance.
• Redemption can be requested once the wallet reaches the minimum threshold (e.g., ₹500).
• Redemptions may be processed via UPI, bank transfer, or other supported methods.
• Processing time for redemptions is typically 3–7 business days.
• Any fraudulent, duplicate, or suspicious activity may result in wallet balance cancellation.
• The wallet is not a substitute for a bank account and cannot be treated as legal tender.`
      },
      {
        title: "Referral Program",
        content: `• Each registered user has a unique referral ID (their mobile number).
• Referral rewards are credited only when the invited user registers successfully and remains active for a minimum period (e.g., 7 days).
• Referral misuse (creating fake accounts, multiple SIM registrations, or self-referrals) is strictly prohibited and may lead to termination of accounts.`
      },
      {
        title: "Discount Coupons & Local Offers",
        content: `• The App may provide discount coupons, deals, or promotional offers from local businesses and advertisers.
• Coupons are subject to expiry dates, redemption limits, and terms set by the respective merchants.
• The App is not responsible for the quality, availability, or fulfillment of any goods or services offered by third-party merchants.
• Users must verify coupon terms before use.`
      },
      {
        title: "Advertisements & Sponsored Content",
        content: `• The App displays ads and sponsored content based on your address, activity, and preferences.
• By using the App, you consent to receive targeted ads, notifications, and promotional messages.
• Clicking ads may redirect you to third-party websites or applications. The App is not responsible for content, policies, or transactions outside our platform.`
      },
      {
        title: "Data Privacy & Security",
        content: `• We collect personal details such as mobile number, address, device activity, and app usage data for functionality, rewards, and ad targeting.
• Your data is processed in accordance with the Information Technology Act, 2000, and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011.
• We use secure systems to store and protect your information.
• We do not sell personal data to unauthorized third parties.
• Users may opt out of promotional messages, subject to certain limitations.`
      },
      {
        title: "User Responsibilities",
        content: `You agree to use the App for lawful purposes only. You must not:
• Manipulate steps using artificial methods.
• Misuse referral rewards.
• Attempt to hack, disrupt, or reverse-engineer the App.
• Post or share inappropriate or harmful content.

Violations may result in suspension or permanent ban.`
      },
      {
        title: "Limitation of Liability",
        content: `• The App relies on mobile sensors and internet connectivity; we do not guarantee 100% accuracy in step counting.
• Rewards are incentives, not guaranteed earnings.
• We are not responsible for:
  ◦ Network issues, technical failures, or system downtime.
  ◦ Merchant offers, discounts, or third-party service failures.
  ◦ Any indirect, incidental, or consequential damages.
• Our maximum liability is limited to the reward balance available in your wallet at the time of dispute.`
      },
      {
        title: "Termination & Suspension",
        content: `• We reserve the right to suspend, block, or terminate accounts involved in fraud, misuse, or violation of these Terms.
• Wallet balances from fraudulent activity will be forfeited without notice.`
      },
      {
        title: "Governing Law & Jurisdiction",
        content: `• These Terms are governed by the laws of India.
• Any disputes shall fall under the exclusive jurisdiction of courts in Hyderabad, Telangana.`
      },
      {
        title: "Amendments",
        content: `• The App reserves the right to update, modify, or amend these Terms & Conditions at any time.
• Users will be notified via in-app alerts, SMS, or email about major changes.
• Continued use of the App after updates implies acceptance of revised Terms.
• Yogic Mile reserves the right to modify, update, or change these Terms & Conditions at any time, without prior notice. Such changes will be effective immediately upon being posted in the "Terms & Conditions" section of the app.
• Users are encouraged to review the Terms regularly to stay informed of updates. Continued use of the app after any changes shall constitute acceptance of the revised Terms.`
      }
    ]
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl h-[90vh] bg-surface/95 backdrop-blur border-border/50">
        <DialogHeader className="pb-2">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-2xl font-bold text-foreground flex items-center gap-2">
              <Shield className="h-6 w-6 text-primary" />
              Legal & Privacy Center
            </DialogTitle>
            <Button variant="ghost" size="icon" onClick={onClose}>
              <X className="h-5 w-5" />
            </Button>
          </div>
        </DialogHeader>

        <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as 'privacy' | 'terms')} className="h-full flex flex-col">
          <TabsList className="grid w-full grid-cols-2 mb-4">
            <TabsTrigger value="privacy" className="flex items-center gap-2">
              <Shield className="h-4 w-4" />
              Privacy Policy
            </TabsTrigger>
            <TabsTrigger value="terms" className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Terms & Conditions
            </TabsTrigger>
          </TabsList>

          <TabsContent value="privacy" className="flex-1 mt-0">
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold text-foreground">Privacy Policy</h2>
                <p className="text-sm text-muted-foreground">
                  Last updated: {privacyPolicyContent.lastUpdated} • Version {privacyPolicyContent.version}
                </p>
              </div>
              <Badge variant="outline" className="text-primary border-primary/50">
                <CheckCircle2 className="h-3 w-3 mr-1" />
                GDPR Compliant
              </Badge>
            </div>

            <ScrollArea className="h-[calc(90vh-200px)]">
              <div className="space-y-6 pr-4">
                <div className="bg-primary/10 p-4 rounded-lg border border-primary/20">
                  <p className="text-sm text-foreground">
                    <strong>Your Privacy Matters:</strong> This policy explains how Yogic Mile collects, uses, 
                    and protects your personal information. We are committed to transparency and your right to 
                    control your data.
                  </p>
                </div>

                {privacyPolicyContent.sections.map((section, index) => (
                  <div key={index} className="space-y-3">
                    <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
                      <span className="w-6 h-6 bg-primary/20 text-primary rounded-full flex items-center justify-center text-sm font-bold">
                        {index + 1}
                      </span>
                      {section.title}
                    </h3>
                    <div className="pl-8">
                      <p className="text-muted-foreground whitespace-pre-line leading-relaxed">
                        {section.content}
                      </p>
                    </div>
                    {index < privacyPolicyContent.sections.length - 1 && <Separator />}
                  </div>
                ))}

                <div className="mt-8 p-4 bg-muted/30 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Questions or Concerns?</h4>
                  <p className="text-sm text-muted-foreground mb-3">
                    If you have any questions about this privacy policy or how we handle your data, 
                    please don't hesitate to contact us.
                  </p>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm">
                      <ExternalLink className="h-3 w-3 mr-1" />
                      Contact Support
                    </Button>
                    <Button variant="outline" size="sm">
                      <FileText className="h-3 w-3 mr-1" />
                      Export My Data
                    </Button>
                  </div>
                </div>
              </div>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="terms" className="flex-1 mt-0">
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold text-foreground">Terms & Conditions</h2>
                <p className="text-sm text-muted-foreground">
                  Last updated: {termsContent.lastUpdated} • Version {termsContent.version}
                </p>
              </div>
              <Badge variant="outline" className="text-secondary border-secondary/50">
                <FileText className="h-3 w-3 mr-1" />
                Legal Agreement
              </Badge>
            </div>

            <ScrollArea className="h-[calc(90vh-200px)]">
              <div className="space-y-6 pr-4">
                <div className="bg-secondary/10 p-4 rounded-lg border border-secondary/20">
                  <p className="text-sm text-foreground">
                    <strong>Important:</strong> By using Yogic Mile, you agree to these terms and conditions. 
                    Please read them carefully as they contain important information about your rights and 
                    responsibilities.
                  </p>
                </div>

                {termsContent.sections.map((section, index) => (
                  <div key={index} className="space-y-3">
                    <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
                      <span className="w-6 h-6 bg-secondary/20 text-secondary rounded-full flex items-center justify-center text-sm font-bold">
                        {index + 1}
                      </span>
                      {section.title}
                    </h3>
                    <div className="pl-8">
                      <p className="text-muted-foreground whitespace-pre-line leading-relaxed">
                        {section.content}
                      </p>
                    </div>
                    {index < termsContent.sections.length - 1 && <Separator />}
                  </div>
                ))}

                <div className="mt-8 p-4 bg-muted/30 rounded-lg">
                  <h4 className="font-semibold text-foreground mb-2">Need Help Understanding These Terms?</h4>
                  <p className="text-sm text-muted-foreground mb-3">
                    Our support team is available to answer any questions about these terms and conditions.
                  </p>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm">
                      <ExternalLink className="h-3 w-3 mr-1" />
                      Contact Legal Team
                    </Button>
                    <Button variant="outline" size="sm">
                      <FileText className="h-3 w-3 mr-1" />
                      Download PDF
                    </Button>
                  </div>
                </div>
              </div>
            </ScrollArea>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};